[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "monots-server"
path = "src/main.rs"

[dependencies]
common = { path = "../../src/common" }
proto = { path = "../../proto" }
monots_core = { path = "../../src/core", package = "monots-core" }
monots-stream = { path = "../../src/stream", package = "monots-stream" }
arrow = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
uuid = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
