[package]
name = "sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common = { path = "../src/common" }
proto = { path = "../proto" }
monots-core = { path = "../src/core" }
tonic = { workspace = true }
arrow = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

[lints]
workspace = true
